"""empty message

Revision ID: 1fafec26192c
Revises: 8bf880a0cc8d
Create Date: 2022-06-01 14:22:58.374173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fafec26192c'
down_revision = '8bf880a0cc8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=sa.JSON(),
               nullable=True)
    op.alter_column('Venue', 'genres',
               existing_type=sa.JSON(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
