"""empty message

Revision ID: b21869e87940
Revises: be9eab28711e
Create Date: 2022-06-01 19:11:42.801937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21869e87940'
down_revision = 'be9eab28711e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Venue', 'seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
