"""empty message

Revision ID: be9eab28711e
Revises: 24ec76e04e1f
Create Date: 2022-06-01 16:07:51.322407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be9eab28711e'
down_revision = '24ec76e04e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.JSON(), nullable=False))
    op.add_column('Venue', sa.Column('genres', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
